version: '3.8'

services:
  # 1. Container Database MariaDB
  mariadb-fpa:
    image: mariadb:latest
    container_name: fpa_mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fpa_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306" # Agar DBeaver dari luar tetap bisa connect
    volumes:
      - mariadb_data:/var/lib/mysql

  # 2. Container Aplikasi Spring Boot
  fpa-backend:
    build: .
    container_name: fpa_backend_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb-fpa
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-fpa:3306/fpa_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mariadb_data: # Menjaga agar data di database TIDAK HILANG saat docker dimatikan