spring.application.name=fpa-portfolio
# Konfigurasi Koneksi Database MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/opex_fpa_db
spring.datasource.username=opex_user
spring.datasource.password=opexpassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Konfigurasi Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pastikan aplikasi membaca dan mengirim data dengan zona waktu UTC
# Mengatur agar serialisasi JSON menggunakan zona waktu pusat UTC+7
spring.jackson.time-zone=Asia/Jakarta